version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: financial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
